export const SET_NAVBAR_LINKS = "SET_NAVBAR_LINKS";
export const SET_NAVBAR_HEIGHT = "SET_NAVBAR_HEIGHT";
export const SET_THEMES = "SET_THEMES";
export const SET_CURRENT_THEME = "SET_CURRENT_THEME";

//FORMS
export const SET_FORM_VALUE = "SET_FORM_VALUE";
