//CONTEXT
export const MAP_TO_NAVBAR = "MAP_TO_NAVBAR";
export const ADD_ANIMATION = "ADD_ANIMATION";
export const REMOVE_ANIMATION = "REMOVE_ANIMATION";
export const INIT_ANIM_LISTENER = "INIT_ANIM_LISTENER";

//FORMS
export const SET_FORM_INPUT = "SET_FORM_INPUT";
export const SET_FORM_INPUT_VALUE = "SET_FORM_INPUT_VALUE";
export const SET_FORM = "SET_FORM";
